name: Deploy Storj pipeline worker

on:
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
  push:
    branches:
      - main
    paths:
      - "workers/storj-bulk-upload/**"
      - ".github/workflows/deploy-storj-pipeline.yml"

jobs:
  deploy-worker:
    name: Deploy storj
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_FULL_EDIT_ACCESS_INCLUDING_BINDINGS }}
          workingDirectory: workers/storj-bulk-upload
          secrets: |
            BACKEND_ADMIN_KEY
        env:
          BACKEND_ADMIN_KEY: ${{ secrets.YRAL_DAPP_BACKEND_APP_ADMIN_AND_PROPOSAL_SUBMITTER_IDENTITY_PRIVATE_KEY }}
