name: Deploy Hot Or Not Game Worker Staging

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - referral_flow
    paths:
      - "workers/yral-hot-or-not/**"
      - ".github/workflows/deploy-hon-worker-staging.yml"

jobs:
  deploy-worker:
    name: Deploy hot or not game staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_FULL_EDIT_ACCESS_INCLUDING_BINDINGS }}
          workingDirectory: workers/yral-hot-or-not
          # not really needed for now, but eh, why not
          secrets: |
            BACKEND_ADMIN_KEY
        env:
          BACKEND_ADMIN_KEY: ${{ secrets.YRAL_DAPP_BACKEND_APP_ADMIN_AND_PROPOSAL_SUBMITTER_IDENTITY_PRIVATE_KEY }}
          ENV: REMOTE
